"""add_feedback_to_chatmessage

Revision ID: 9e6b94f59fa1
Revises: df68f4d13c77
Create Date: 2026-05-30 13:48:49.308544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6b94f59fa1'
down_revision: Union[str, Sequence[str], None] = 'df68f4d13c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('feedback', sa.Boolean(), nullable=True, comment='用户反馈：True=赞, False=踩, None=无反馈'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'feedback')
    # ### end Alembic commands ###
